# nodejs-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: finalns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: emanabdelhamed241/node-app-final:latest
        ports:
        - containerPort: 3001

---
# nodejs-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: finalns

spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
